### ISSUE TITLE
 주제 선정하기

### ISSUE THREAD

**Issue by 22200668seongeun** [2023OSSLteamproject/MusicList#1]
후보

1.과일 메뉴 CRUD
과일종류 유통기한 제조기한 

2.세탁정보 CRUD
옷종류 /세탁 / 탈수 / 건조 여부

**Comment by hzlloni** [comment]
1.노래플레이리스트 CRUD
순번 /  노래제목 /  가수명 / 

2. 시간표 CRUD
시간 /  강의명/ 교수님/강의장소

**Comment by 22200668seongeun** [comment]
의견 종합 결과 노래 플레이리스트로 결정합니다.

**Comment by hzlloni** [comment]
좋습니다
