### ISSUE TITLE
프로젝트 설계 기획 

### ISSUE THREAD

**Issue by 22200668seongeun** [2023OSSLteamproject/MusicList#2]
- [x] CRUD 기능, 데이터 파일 저장/읽어오기, 검색 메뉴(종료메뉴 제외) 등 (총 메뉴 8개 이상)

- [x] 구조체로 한 세트의 데이터 정의 및 10개 이상 함수 정의 및 개발

**Comment by hzlloni** [comment]
그러면 데이터파일저장 검색 총 2개랑
추가기능, 삭제기능, 수정기능 3개 총 5개에다가 3개 기능 더 넣으면 좋을 것 같아

**Comment by 22200668seongeun** [comment]
좋아! 그럼 메뉴를 보는 것도 넣자

**Comment by hzlloni** [comment]
그러면 하나는 노래듣기 메뉴를 넣으면 어때? 노래듣기 메뉴를 누르면 나중에 메뉴보기를 했을때 재생한횟수가 +1씩 늘어나는거야!
아니면 노래다운로드 기능도 좋은것 같아 만약 노래다운로드메뉴를 누른다면 노래다운여부가 N에서 Y로 바뀌게 되는 기능 !
두개 중에 무슨 기능이 더 나을까?

**Comment by 22200668seongeun** [comment]
둘다 해도될 것 같아! 둘다 메뉴에 넣자

**Comment by hzlloni** [comment]
그래그래 그러면 메뉴는 다정했고, 다음 구조체로 데이터 정의해보자

**Comment by 22200668seongeun** [comment]
잠깐 정리하고 갈게  

메뉴 

1. 데이터파일
2. 검색
3. 메뉴보기 
4. 노래 추가
5. 노래 삭제
6. 노래 수정
7. 노래다운로드
8. 노래듣기

**Comment by hzlloni** [comment]
여기다가 우리 종료버튼 하나도 있어서 CRUD종료할 수 있게하면 좋을것같아

**Comment by 22200668seongeun** [comment]
아하 수정할게

메뉴

1. 데이터파일 추가
2. 검색
3. 메뉴보기
4. 노래 추가
5. 노래 삭제
6. 노래 수정
7. 노래다운로드
8. 노래듣기 
9. 종료

**Comment by hzlloni** [comment]
그러면 우리가 메뉴보기를 눌렀을 때,상단바에서 보여주는 것이 
순번/노래제목/가수명/재생한횟수 / 노래다운여부 /메모 이렇게 되면 좋을 것 같아 이걸 구조체 한세트로 정의할까?

**Comment by 22200668seongeun** [comment]
좋아  구조체로 정의하면 이렇게 될것같아 

typedef struct{
   char title[20];
   char name[20];
   int number;
   char Down;
   char memo[40];
}Music;

**Comment by hzlloni** [comment]
넹넹 함수는 이렇게 정의하겠습니다~~

int selectMenu(); //처음에 메뉴를 선택할 수 있게 보여주는 함수
void readMusic(Music m); //상단바에서 보여주는 모든 것을 읽는 함수 
int addMusic(Music *m); //음악을 추가하는 함수
void listMusic(Music *m[], int count); //현 음악리스트를 보여주는 함수
void deleteMusic(Music *m[], int count); //음악을 플레이리스트에서 삭제하는 함수
void updateMusic(Music *m); //플레이리스트를 수정하는 함수
void downMusic(Music *m[], int count); //노래다운로드 하는 함수
void listenMusic(Music *m[], int count); //노래듣는 함수
void searchMusic(Music *m[], int count); //음악을 검색하는 함수
void saveData(Music *m[], int count); //데이터를 파일에 저장하는 함수
int loadData(Music *m[]); //파일에 저장된 데이터를 불러오는 함수

**Comment by 22200668seongeun** [comment]
그 노래 듣는 함수를 노래 재생 횟수 함수로 고치는게 나을것같아 그 listenMusic은 그대로 둘까?

**Comment by hzlloni** [comment]
그러면 listenMusic은 그대로 두고 노래재생횟수함수 이렇게 고칠까?

**Comment by 22200668seongeun** [comment]
그래  이렇게하자! 

int selectMenu(); //처음에 메뉴를 선택할 수 있게 보여주는 함수
void readMusic(Music m); //상단바에서 보여주는 모든 것을 읽는 함수
int addMusic(Music *m); //음악을 추가하는 함수
void listMusic(Music *m[], int count); //현 음악리스트를 보여주는 함수
void deleteMusic(Music *m[], int count); //음악을 플레이리스트에서 삭제하는 함수
void updateMusic(Music *m); //플레이리스트를 수정하는 함수
void downMusic(Music *m[], int count); //노래다운로드 하는 함수
void listenMusic(Music *m[], int count); //노래 재생 횟수 함수
void searchMusic(Music *m[], int count); //음악을 검색하는 함수
void saveData(Music *m[], int count); //데이터를 파일에 저장하는 함수
int loadData(Music *m[]); //파일에 저장된 데이터를 불러오는 함수

**Comment by 22200668seongeun** [comment]
데이터 파일을 조회하는 건 필요가 없다고 해서 loaddata는 빼기로 하자 

int selectMenu(); //처음에 메뉴를 선택할 수 있게 보여주는 함수
void readMusic(Music m); //상단바에서 보여주는 모든 것을 읽는 함수
int addMusic(Music *m); //음악을 추가하는 함수
void listMusic(Music *m[], int count); //현 음악리스트를 보여주는 함수
void deleteMusic(Music *m[], int count); //음악을 플레이리스트에서 삭제하는 함수
void updateMusic(Music *m); //플레이리스트를 수정하는 함수
void downMusic(Music *m[], int count); //노래다운로드 하는 함수
void listenMusic(Music *m[], int count); //노래 재생 횟수 함수
void searchMusic(Music *m[], int count); //음악을 검색하는 함수
void saveData(Music *m[], int count); //데이터를 파일에 저장하는 함수

**Comment by 22200668seongeun** [comment]
> 아하 수정할게
> 
> 메뉴
> 
> 1. 데이터파일
> 2. 읽어오기
> 3. 검색
> 4. 메뉴보기
> 5. 노래 추가
> 6. 노래 삭제
> 7. 노래 수정
> 8. 노래다운로드
> 9. 노래듣기
> 10. 종료
