### ISSUE TITLE
프로젝트 코드 짜기

### ISSUE THREAD

**Issue by hzlloni** [2023OSSLteamproject/MusicList#5]
우리 지금 설정한 메뉴에서 조회를 할 수 있는 버튼을 추가하면 좋을 것 같아

**Comment by 22200668seongeun** [comment]
그래! 
헤더파일에 추가한 int selectNum();은 무슨 함수인지 알수있을까?

**Comment by hzlloni** [comment]
원래 메뉴에서 번호를고르는 함수를 따로 만들어서 받으려고 했는데 
필요없어서 지웠는데 헤더파일에는 안지운것 같아 ! 지울게 !

**Comment by 22200668seongeun** [comment]
그래 알겠어! 그리고 메인함수에서 deleteMusic 함수에 count 매개변수를 추가했어! 이를 이용해 data가 유효한 범위 내의 번호인지 확인해야할것같아서. 또한 헤더함수와 라이브러리함수도 고칠게
