### ISSUE TITLE
오류수정 

### ISSUE THREAD

**Issue by 22200668seongeun** [2023OSSLteamproject/MusicList#6]
오류수정해야할것 말해보자

**Comment by 22200668seongeun** [comment]
수정하고 다시 리스트를 조회 시 노래다운의 경우가 출력되지않아

**Comment by hzlloni** [comment]
처음에 수정할때 다운여부가 입력해도 안뜨길래 앞에 공백 넣어주니깐 해결됐어 !
scanf(" %c", &m[index - 1]->down);

**Comment by 22200668seongeun** [comment]
파일을 열었을 시 모든 번호가 한 줄로 표시 되어 읽혀

**Comment by hzlloni** [comment]
그래서 \n을 넣어서 한줄읽고 다음줄로 넘어가게 했어

**Comment by 22200668seongeun** [comment]
그리고 메인함수에서 deleteMusic 함수에 count 매개변수를 추가해서 수정했어.

**Comment by hzlloni** [comment]
지금까지 다 잘돌아가는 것 같아 !!
